[build.environment]
  NODE_VERSION = "18"

[build]
  publish = "output"
  command = "pnpm run build"

[functions]
  directory = "functions/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "pnpm dev"
  port = "8888"
  publish = "nuxt"